### ISSUE TITLE
KDE Now fails to load, Error loading QML file.

### ISSUE THREAD

**Issue by mzs112000** [g33kyaditya/KDE-Now#18]
![screenshot_20160713_130748](https://cloud.githubusercontent.com/assets/8335935/16818224/8c2ae7a8-48fb-11e6-88fd-4970bbbb7634.png)
I cloned the github repo on July 13th, then I did a "cmake .", then a "sudo make install", and then I added the plasmoid to the deskto and I got an error saying that it failed to load a QML file. I have attached a screenshot.

My specs are:
Archlinux with kernel 4.6.4, nVidia 340.96 proprietary driver, on Dell Precision M4400
KDE Plasma 5.7.1, KDE Frameworks 5.24, KDE Applications 16.04, QT 5.7, 64-Bit with multilib enabled.
I have a Core 2 Duo P8700 2.50GHz, and 2GB DDR2 800MHz.

**Comment by g33kyaditya** [comment]
Actually, the software is still under development, and it's no where close to a working prototype. I need some more time, to get things done. Thanks for trying it out though :)

**Comment by g33kyaditya** [comment]
Actually, the software is still under development, and it's no where close to a working prototype. I need some more time, to get things done. Thanks for trying it out though :)
