### ISSUE TITLE
Contribute.md and License.md file missing

### ISSUE THREAD

**Issue by rusrushal13** [g33kyaditya/KDE-Now#23]
How to contribute into this repo?
Could I add MIT License to it?

**Comment by g33kyaditya** [comment]
Actually, the license is GPL 3. You could add it to the License.md file. Also, I plan to make this a read only mirror of the KDE git repo https://quickgit.kde.org/?p=kde-now.git . If you want to make these changes, submit a PR now. Later I'll make the repo read-only
